#!/usr/bin/env bash

# MONITORS #
monitors=($(bspc query -M --names))
desktops=$(expr 10 / ${#monitors[@]})
start=1
end=$desktops
for monitor in ${monitors[@]}; do
    bspc monitor $monitor -d $(seq -s ' ' $start $end)
    start=$(expr $start + $desktops)
    end=$(expr $end + $desktops)
done

# CONFIGURATION #


# Dracula theme #

bspc config focused_border_color "#bd93f9"

# AUTOSTART #
feh --bg-fill ~/.config/wallpaper/dracula.png
