#!/usr/bin/env bash

# MONITORS #
if [[ "$(uname -n)" == *'desktop'* ]]; then
    bspc monitor HDMI-0 -d 1 2 3 4 5
    bspc monitor HDMI-1 -d 6 7 8 9 10
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

# CONFIGURATION #

bspc config border_width 2
bspc config window_gap 5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# Dracula theme #

bspc config focused_border_color "#bd93f9"

# WINDOW RULES #
bspc rule -a Steam state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

# AUTOSTART #
[[ ! $(pidof -x sxhkd) ]] && sxhkd &
feh --bg-fill ~/.dotfiles/config/wallpaper/base.png
