#!/bin/bash

# MONITORS #
if [ "$(uname -n)" = 'arch-desktop' ]; then
	bspc monitor HDMI-0 -d 1 2 3 4 5
	bspc monitor HDMI-1 -d 6 7 8 9 10
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

# CONFIGURATION #

bspc config border_width         2
bspc config window_gap          7
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Dracula theme #

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

# WINDOW RULES #
bspc rule -a Steam state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

# PROBLEMS WITH JAVA APPLICATIONS #
wmname LG3D

# AUTOSTART #
[[ ! $(pidof -x sxhkd) ]] && sxhkd &
[[ ! $(pidof -x picom) ]] && picom --experimental-backends &

feh --bg-tile ~/Pictures/Wallpapers/avatar.png
kdeconnect-cli --refresh && kdeconnect-cli -l >/dev/null
sh ~/.config/polybar/launch.sh &
[[ ! $(pidof -x cloud-drive-daemon) ]] && synology-drive &

